INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (1, 'FCL / Full Konteyner', 'fcl-full-konteyner');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (2, 'LCL / Parsiyel Konteyner', 'lcl-parsiyel-konteyner');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (3, 'Transit Taşımacılık', 'transit-tasmaclk');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (4, 'Çapraz Sevkiyat', 'capraz-sevkiyat');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (5, 'Üçüncü Ülke Yük Taşıma Organizasyonları', 'ucuncu-ulke-yuk-tasma-organizasyonlar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (6, 'Dökme Açık Gemi Yüklemeleri', 'dokme-ack-gemi-yuklemeleri');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (7, 'Intermodal Taşımacılık', 'intermodal-tasmaclk');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (8, 'Tehlikeli Maddelerin Taşınması', 'tehlikeli-maddelerin-tasnmas');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (9, 'Kapıdan Kapıya Taşımalar', 'kapdan-kapya-tasmalar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (10, 'Lowbed Taşımalar', 'lowbed-tasmalar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (11, 'Frigorifik Taşımalar', 'frigorifik-tasmalar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (12, 'Gümrükleme ve Depolama Hizmetleri', 'gumrukleme-ve-depolama-hizmetleri');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (13, 'Genel Kargo Taşımaları', 'genel-kargo-tasmalar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (14, 'Chartering Hizmetleri', 'chartering-hizmetleri');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (15, 'Avrupa, Balkanlar, Orta Doğu ve Baltık ülkeleri ile Türkiye arasındaki demiryolu taşımacılık çözümleri', 'avrupa-balkanlar-orta-dogu-ve-baltk-ulkeleri-ile-turkiye-arasndaki-demiryolu-tasmaclk-cozumleri');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (16, 'Askeri Araçlar', 'askeri-araclar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (17, 'Silahlar', 'silahlar');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (18, 'Mühimmat', 'muhimmat');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (19, 'Gümrüklü, Gümrüksüz Depolama', 'gumruklu-gumruksuz-depolama');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (20, 'Kapalı, Açık Depolama', 'kapal-ack-depolama');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (21, 'Tehlikeli Madde Depolama', 'tehlikeli-madde-depolama');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (22, 'Soğuk Hava Depolama', 'soguk-hava-depolama');
INSERT INTO item_sunulanhizmetler (id, text, slug) VALUES (23, 'Elleçleme, Paketleme, Barkodlama, Etiketleme Hizmetleri', 'ellecleme-paketleme-barkodlama-etiketleme-hizmetleri');