# Generated by Django 3.1 on 2020-09-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_auto_20200926_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kariyer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kariyer',
            name='updated_by',
        ),
    ]
