# Generated by Django 3.1 on 2020-09-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0003_auto_20200926_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kariyer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kariyer',
            name='updated_at',
        ),
    ]
