# Generated by Django 3.1 on 2020-09-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetler',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
