# Generated by Django 3.1 on 2020-09-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200929_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunulanHizmetler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Sunulan Hizmetler',
                'verbose_name_plural': 'Sunulan Hizmetler',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='hizmetler',
            name='sunulanHizmet',
            field=models.ManyToManyField(blank=True, to='item.SunulanHizmetler', verbose_name='Sunulan Hizmetler'),
        ),
    ]
