# Generated by Django 3.1 on 2020-09-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200929_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hizmetler',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hizmetler',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hizmetler',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hizmetler',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sunulanhizmetler',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sunulanhizmetler',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sunulanhizmetler',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sunulanhizmetler',
            name='updated_by',
        ),
    ]
