# Generated by Django 3.1 on 2020-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200929_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetler',
            name='resim1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Resim 1'),
        ),
    ]
