# Generated by Django 3.1 on 2020-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_hizmetler_resim1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetler',
            name='ekaciklama',
            field=models.TextField(null=True, verbose_name='Ek Açıklama'),
        ),
        migrations.AddField(
            model_name='hizmetler',
            name='resim2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Resim 2'),
        ),
    ]
